# Generated by Django 5.2.15 on 2026-06-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invoice_billing_address_invoice_billing_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='pcs', max_length=20),
        ),
    ]
